/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 10.0
      io_method: "mmap"
      frame_id: "camera_link"
      pixel_format: "yuyv"
      color_format: "yuv422p"
      image_width: 640
      image_height: 480
      camera_name: "camera"
      camera_info_url: "package://husky_interbotix/params/camera_info.yaml"
